#加密解密地址
supportUrl :
    sign_encrypt_url : http://10.10.10.23:8081/sign_and_encrypt
    decrypt_and_verify_url : http://10.10.10.23:8081/decrypt_and_verify
#实时接口地址
realTime_interface:
    common : http://10.10.10.185:10003/services/cgbiz/
#页面接口地址
page_interface:
    submit_url : http://10.10.10.185:9008/dep-page-service/submit
    submitAll_url : http://10.10.10.185:9008/dep-page-service/submitAll
    common_send_message_url : http://10.10.10.185:9008/dep-page-service/sendSms?
    request_validateParam_url : http://10.10.10.185:9008/dep-page-service/validateParam
    common : http://10.10.10.185:9008/dep-page-service/
excel:
    case_path : 'E:\\Git\\JYTest\\testdata\\interface\\case.xlsx'
#邮件配置
email:
    email_server : smtp.163.com
    email_on_off : 'off'
    email_sender : 18392169938@163.com
    email_password :
    email_receiver : wangqunsong@jytpay.com
    email_subject : 'JYT--接口测试报告'
    email_content :
#日志配置
log:
    file_name : test.log
    backup : 5
    console_level : WARNING
    file_level : DEBUG
    pattern : '%(asctime)s - %(name)s - %(levelname)s - %(message)s'